image: python:3.8-buster


before_script:
  - export GOTO_NUM_THREADS=1
  - pip install scipy cython numpy pandas
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -e .

stages:
    - style
    - test_code
    - test_cli    
    - test_and_create_docs
    - publish_docs

style:
    script:
        - flake8 .
    allow_failure: true
    stage: style


tests:
    script:
        - tox -r -vv
        - coverage report -m
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    stage: test_code
    artifacts:
           paths:
             - htmlcov/


test_cli:
    script:
        - {{ cookiecutter.repo_name }}
    stage: test_cli

docs:
    script:
        - tox -e docs
    stage: test_and_create_docs
    dependencies:
          - tests
    artifacts:
           paths:
             - docs/_build

publish_docs:
    script:
        - publish_docs docs/_build/html {{ cookiecutter.repo_name }}
        - create_index_html
    when: manual
    stage: publish_docs
    dependencies:
          - docs
    only:
        - master
