stages:
    - style
    - test_code
    - test_and_create_docs
    - publish_docs

style:
    tags:
        - python
    script:
        - pyenv local $(latest_python 3.7)
    allow_failure: true
    stage: style


tests:
    tags:
        - python
    script:
        - pyenv versions
        - pyenv local $(latest_python 2.7) $(latest_python 3.7)
        - tox -r -vv
        - coverage report -m
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    stage: test_code
    artifacts:
           paths:
             - htmlcov/

docs:
    tags:
        - python
    script:
        - pyenv local $(latest_python 3.7)
        - tox -e docs
    stage: test_and_create_docs
    dependencies:
          - tests
    artifacts:
           paths:
             - docs/_build

publish_docs:
    tags:
        - python
    script:
        - publish_docs docs/_build/html {{ cookiecutter.repo_name }}
        - create_index_html
    when: manual
    stage: publish_docs
    dependencies:
          - docs
    only:
        - master
